spring:
  application:
    name: ImoocMerchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3307//passbook?autoReconnect=true
    username:root
    password:root
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527
logging:
  level: debug
  file: imooc-merchants.log



spring.datasource.url=jdbc:mysql://127.0.0.1:3307/passbook
spring.datasource.username=root
spring.datasource.password=root