spring:
  application:
    name: Imooc-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/passbook?autoReconnect=true&useSSL=false
    username: root
    password: root
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///Users
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379


  server:
    port: 9528

  logging:
    file: imooc-passbook.log
    level: debug
